### ISSUE TITLE
【改进建议】兼容谷歌搜索结果的复制链接文本功能

### ISSUE THREAD

**Issue by httpsColon** [zzm-note/SuperDrag#15]
![image](https://github.com/zzm-note/SuperDrag/assets/102579986/4bf126e3-e380-4de2-88e0-9384ad140613)

**Comment by httpsColon** [comment]
谷歌的搜索结果标题文本在<h3>标签里，this._dic['keywords'] = this.dragEvent.srcElement.parentNode.href; 这样获取不到

**Comment by zzm-note** [comment]
> 谷歌的搜索结果标题文本在h3标签里，this._dic['keywords'] = this.dragEvent.srcElement.parentNode.href; 这样获取不到

3.7.3版本修复了，等待发布
