### ISSUE TITLE
希望增加拖拽生成二维码功能

### ISSUE THREAD

**Issue by HookCode** [zzm-note/SuperDrag#3]
应用场景：
选中文字拖拽生成二维码，手机扫描可以直接复制
选中链接拖拽生成二维码，手机扫码可以查看或者打开链接

**Comment by zzm-note** [comment]
> 应用场景： 选中文字拖拽生成二维码，手机扫描可以直接复制 选中链接拖拽生成二维码，手机扫码可以查看或者打开链接

需求可以再具体一点，譬如生成后怎么处理

**Comment by HookCode** [comment]
![001](https://user-images.githubusercontent.com/90203620/148572882-c76babb4-af5e-485e-8b68-07d35cc1f9e8.gif)
生成后点击空白地方自动消失

**Comment by zzm-note** [comment]
> ![001](https://user-images.githubusercontent.com/90203620/148572882-c76babb4-af5e-485e-8b68-07d35cc1f9e8.gif) 生成后点击空白地方自动消失

了解，有空再做吧

**Comment by zzm-note** [comment]
已经添加了该功能，待上架微软扩展商店。

**Comment by HookCode** [comment]
感谢开发，生成二维码功能在其他Chrome内核浏览器下不兼容，之前版本的功能正常使用


测试浏览器 Vivaldi | 5.0.2497.35 (Stable channel)

**Comment by zzm-note** [comment]
> 感谢开发，生成二维码功能在其他Chrome内核浏览器下不兼容，之前版本的功能正常使用
> 
> 测试浏览器 Vivaldi | 5.0.2497.35 (Stable channel)

已修复

**Comment by HookCode** [comment]
> > 感谢开发，生成二维码功能在其他Chrome内核浏览器下不兼容，之前版本的功能正常使用
> > 测试浏览器 Vivaldi | 5.0.2497.35 (Stable channel)
> 
> 已修复

谢谢 可以了
