### ISSUE TITLE
在edge中，设置界面突然不显示了

### ISSUE THREAD

**Issue by ffplayer** [zzm-note/SuperDrag#4]
![drag](https://user-images.githubusercontent.com/4073704/160246109-b1f42dae-4f0b-4eaa-bf1b-687d1c7e718f.png)
如图所示。

Microsoft Edge 版本 99.0.1150.52 (正式版本) (64 位)

不知道其它人有没有遇到过这问题

**Comment by zzm-note** [comment]
已经修复了
